### ISSUE TITLE
Update Sample Retrieval notebook to use Pycytominer SingleCells

### ISSUE THREAD

**Issue by bethac07** [ciminilab/2022_Garcia-Fossa_submitted#3]
Pycytominer [contains a function for loading single cell data from a database](https://github.com/cytomining/pycytominer/blob/master/pycytominer/cyto_utils/cells.py) ; you essentially always want to use this rather than loading the data as you did in this notebook a) because it's easier (you just call the string below, and then subset the data how you like) and b) merging based on ObjectNumber is not actually reliable - CellProfiler numbers the objects based purely on which one is higher in the image (and then left-to-right), so you can get ObjectNumber mismatches ala the picture below.

We've run tests in the past and this isn't INCREDIBLY frequent, but it does happen a measurable fraction of the time. As such, I don't think it will LIKELY affect the figures in Basic Protocol 2, but especially if we want this to be an example of how people should handle their own data, we should model doing it the best way.

```
from pycytominer.cyto_utils.cells import SingleCells
df = SingleCells(f"sqlite:///{backend_file}")
```

<img width="455" alt="image" src="https://user-images.githubusercontent.com/6721515/202302398-3930a227-44df-4ef0-bae9-ba436f52ffda.png">

**Comment by bethac07** [comment]
```
from pycytominer.cyto_utils.cells import SingleCells
database = SingleCells(f"sqlite:///{backend_file}")
df = database.merge_single_cells()
```

**Comment by fefossa** [comment]
I've been trying to run with SingleCells on my PC (16 GB RAM) and it doesn't finish (after 30 min gives an error about not having enough memory to allocate to). I've also tried running it in a Google Colab notebook and also gives an error about the memory (says I should buy Colab Pro). 

@mccruz07 ran in his mac m1 and it took about 10 minutes to run, it can generate the dataframe fine so the code works, but it uses about 40 GB of memory to do it.

I've updated [the notebook ](https://github.com/ciminilab/2022_Garcia-Fossa_submitted/blob/main/basic_protocol_2/notebook/support%20notebooks/1_Samples_retrieval.ipynb) with two options: 
(1) to use SingleCells (with a note on how much memory it would need to run)
(2) the code we were using before to subsample from the database (to be able to run and replicate for the paper).

Do you think that would be ok @bethac07?

**Comment by bethac07** [comment]
Makes perfect sense to me!
