### ISSUE TITLE
Add dropdown to section 5

### ISSUE THREAD

**Issue by fefossa** [ciminilab/2022_Garcia-Fossa_submitted#5]
Add a "select which thing is the negative control" nice little dropdown in section 4 or 5 based on the piece of metadata chosen in 4.1 and then use that in section 5 rather than needing to edit code (now the user needs to change "strata" parameter inside corr function)

**Comment by bethac07** [comment]
I think you could either directly copy the one that's in 5.1, or move it up a section - your preference (5.1 and 5.2 both have independent ones, so perhaps you want one in each?

**Comment by bethac07** [comment]
Oops, sorry, closed early - one left, "should be rescaled?"
